### ISSUE TITLE
facilities에 dispatch(save10Location(sliceData)); 부분때문에 Warning이 생성되어 무한루프 가능성을 제기

### ISSUE THREAD

**Issue by pigrok** [kimhwanhoon/20230724_team_project#45]
facilities에 dispatch(save10Location(sliceData)); 부분때문에 Warning이 생성되어 무한루프 가능성을 제기함.
=> 해결한 방법
앞서 필터링에 사용한 useEffect 안으로 아래 로직을 옮겨줌으로서 해결함
 
// 현재 페이지에 따라 보여줄 데이터 조각 설정
    const startIndex = (currentPage - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    const sliceData = sortPublicDataByDis.slice(startIndex, endIndex);
    // 필터된 데이터들을 스토어에 저장
    dispatch(save10Location(sliceData));

=> 옮겨준 useEffect 코드부분
/ 거리 기준으로 데이터 정렬하는 부분

  useEffect(() => {
    const sortPublicDataByDis = [...filteredData].sort((a, b) => {
      const dx = calDistance(location.longitude, location.latitude, a.X, a.Y);
      const dy = calDistance(location.longitude, location.latitude, b.X, b.Y);
      return dx - dy; // 거리 값을 비교하여 정렬
    });
    setSortPublicDataByDis(sortPublicDataByDis);
    // 현재 페이지에 따라 보여줄 데이터 조각 설정
    const startIndex = (currentPage - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    const sliceData = sortPublicDataByDis.slice(startIndex, endIndex);
    // 필터된 데이터들을 스토어에 저장
    dispatch(save10Location(sliceData));
    dispatch(setSortedData(sortPublicDataByDis));
    // Update the sliceData state
    setSliceData(sliceData);
  }, [dispatch, currentPage, itemsPerPage, filteredData, location, globalSearch]);

해당 부분 수정하였습니다.

**Comment by xoxojw** [comment]
성록님이 해결해주셔서 이슈 close 해두겠습니다!
